# Generated by Django 4.2.14 on 2025-12-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='father_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
