# Generated by Django 4.2.14 on 2025-12-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_client_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
