# Generated by Django 4.2.14 on 2025-12-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_client_father_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='father_name',
            new_name='Father_Name',
        ),
    ]
