# Generated by Django 4.2.27 on 2026-01-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gstdetails_created_by_gstdetails_gst_scheme_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='casual_leave',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='employee',
            name='earned_leave',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_leave',
            field=models.FloatField(default=7.0),
        ),
    ]
